name: tests

on: [push]


jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        
      - name: Install package dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements.txt
          
      - name: Install testing dependencies
        run: pip install -U pytest
        
      - name: Run tests with pytest
        run: python -m pytest
        
